modLoader = "neoforge"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL="" #optional
displayURL = "${display_url}" #optional
logoFile = "${logo_file}" #optional
credits = "${credits}"
authors = "${mod_authors}"
description = '''${mod_description}'''
#displayTest=""

[[dependencies."${mod_id}"]]
modId = "neoforge"
mandatory = true
versionRange = "${neoforge_version_range}"
ordering = "NONE" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
side="BOTH" # Physical side this dependency is applied on - BOTH, CLIENT or SERVER
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${neoforge_minecraft_version_range}"
ordering = "NONE"
side = "BOTH"